"""TDD test for scripts/split_bdd_scenarios.py (v2): emits .feature files."""

from __future__ import annotations
from pathlib import Path
import subprocess
import sys


ROOT = Path(__file__).resolve().parents[3]
SCRIPT = ROOT / "scripts" / "split_bdd_scenarios.py"


def test_emits_feature_file_for_router_tag(tmp_path):
    out_int = tmp_path / "integration"
    out_eval = tmp_path / "eval"
    res = subprocess.run(
        [
            sys.executable,
            str(SCRIPT),
            "--apply",
            "--integration-out",
            str(out_int),
            "--eval-out",
            str(out_eval),
        ],
        capture_output=True,
        text=True,
        check=False,
    )
    assert res.returncode == 0, res.stderr
    router = out_int / "features" / "router.feature"
    assert router.exists(), f"missing {router}"
    text = router.read_text(encoding="utf-8")
    assert text.startswith("# AUTOGENERATED"), "missing header"
    assert "Feature: IntentRouter" in text
    assert "@router" in text
    assert "Scenario:" in text
    # The integration bucket receives the timeout/fallback scenario.
    assert "回退 clarify" in text


def test_no_pytest_skip_stub_emitted(tmp_path):
    out_int = tmp_path / "integration"
    out_eval = tmp_path / "eval"
    subprocess.run(
        [
            sys.executable,
            str(SCRIPT),
            "--apply",
            "--integration-out",
            str(out_int),
            "--eval-out",
            str(out_eval),
        ],
        check=True,
    )
    # Old behaviour wrote test_bdd_*.py -- new behaviour must not.
    assert not any(out_int.glob("test_bdd_*.py")), (
        "splitter still emitting pytest.skip stubs"
    )
    assert not any(out_eval.glob("test_bdd_*.py")), (
        "splitter still emitting pytest.skip stubs"
    )
