// [SPEC-A-006] REST API route registry (SPEC-1A) -- TypeScript mirror of
// src/shared/contracts/api_routes.py. Authority: docs/specs/SPEC-A-contracts.md
// SPEC-1A "API 路由总表". 24 REST + 1 WebSocket = 25 entries total.

export type RouteType = 'rest' | 'websocket';

export type HttpMethod = 'GET' | 'POST' | 'PUT' | 'DELETE' | 'WS';

export interface ApiRouteEntry {
  type: RouteType;
  method: HttpMethod;
  path: string;
  description: string;
  callers: readonly string[];
  request_schema: string | null;
  response_schema: string;
  error_response_schema: 'ErrorResponse' | null;
  constraints: Record<string, unknown>;
  query_params: Record<string, { type: string; default: unknown }>;
}

const ERR = 'ErrorResponse' as const;

export const API_ROUTES: readonly ApiRouteEntry[] = [
  // --- Projects: list / CRUD ---
  {
    type: 'rest',
    method: 'GET',
    path: '/api/projects',
    description: 'List projects (paginated in V1.5).',
    callers: ['frontend: project-list'],
    request_schema: null,
    response_schema: 'ProjectListResponse',
    error_response_schema: null,
    constraints: {},
    query_params: {},
  },
  {
    type: 'rest',
    method: 'POST',
    path: '/api/projects',
    description: 'Create project; description must be >= 10 characters.',
    callers: ['frontend: new-project-wizard'],
    request_schema: 'CreateProjectRequest',
    response_schema: 'CreateProjectResponse',
    error_response_schema: ERR,
    constraints: { description_min_chars: 10 },
    query_params: {},
  },
  {
    type: 'rest',
    method: 'GET',
    path: '/api/projects/{id}',
    description: 'Project detail.',
    callers: ['frontend: project-detail'],
    request_schema: null,
    response_schema: 'ProjectInfo',
    error_response_schema: null,
    constraints: {},
    query_params: {},
  },
  {
    type: 'rest',
    method: 'DELETE',
    path: '/api/projects/{id}',
    description: 'Soft-delete project.',
    callers: ['frontend: project-list'],
    request_schema: null,
    response_schema: 'OkResponse',
    error_response_schema: ERR,
    constraints: { soft_delete: true },
    query_params: {},
  },

  // --- Projects: workflow FSM ---
  {
    type: 'rest',
    method: 'GET',
    path: '/api/projects/{id}/state',
    description: 'Full ProjectState for frontend state restoration.',
    callers: ['frontend: workflow-page'],
    request_schema: null,
    response_schema: 'ProjectState',
    error_response_schema: null,
    constraints: {},
    query_params: {},
  },
  {
    type: 'rest',
    method: 'POST',
    path: '/api/projects/{id}/advance',
    description: 'Advance to next phase (idempotent; see SPEC-3.7).',
    callers: ['frontend: advance-button'],
    request_schema: 'AdvanceRequest',
    response_schema: 'AdvanceResponse',
    error_response_schema: ERR,
    constraints: { idempotent: true },
    query_params: {},
  },
  {
    type: 'rest',
    method: 'POST',
    path: '/api/projects/{id}/skip',
    description: 'Skip current phase (P5/P6 only per SPEC-1A).',
    callers: ['frontend: skip-button'],
    request_schema: null,
    response_schema: 'SkipResponse',
    error_response_schema: ERR,
    constraints: { allowed_phases: [5, 6] },
    query_params: {},
  },
  {
    type: 'rest',
    method: 'POST',
    path: '/api/projects/{id}/rollback',
    description: 'Roll back to a target phase; invalidates downstream.',
    callers: ['frontend: rollback-action'],
    request_schema: 'RollbackRequest',
    response_schema: 'RollbackResponse',
    error_response_schema: ERR,
    constraints: {},
    query_params: {},
  },
  {
    type: 'rest',
    method: 'POST',
    path: '/api/projects/{id}/chat',
    description: 'Send conversation message (routed by IntentRouter).',
    callers: ['frontend: chat-input'],
    request_schema: 'ChatRequest',
    response_schema: 'ChatResponse',
    error_response_schema: ERR,
    constraints: { routed_by: 'IntentRouter' },
    query_params: {},
  },

  // --- Projects: tasks ---
  {
    type: 'rest',
    method: 'GET',
    path: '/api/projects/{id}/tasks',
    description: 'Task ledger list for the project.',
    callers: ['frontend: task-panel'],
    request_schema: null,
    response_schema: 'TaskListResponse',
    error_response_schema: null,
    constraints: {},
    query_params: {},
  },
  {
    type: 'rest',
    method: 'POST',
    path: '/api/projects/{id}/tasks/{task_id}/cancel',
    description: 'Cancel a task (pending/queued states only).',
    callers: ['frontend: task-panel'],
    request_schema: null,
    response_schema: 'OkResponse',
    error_response_schema: ERR,
    constraints: { cancellable_states: ['pending', 'queued'] },
    query_params: {},
  },

  // --- Projects: preferences & artifacts ---
  {
    type: 'rest',
    method: 'GET',
    path: '/api/projects/{id}/preferences',
    description: 'Get per-project preferences payload.',
    callers: ['frontend: preferences-confirm-ui'],
    request_schema: null,
    response_schema: 'Preferences',
    error_response_schema: null,
    constraints: {},
    query_params: {},
  },
  {
    type: 'rest',
    method: 'POST',
    path: '/api/projects/{id}/preferences/confirm',
    description: 'Confirm candidate preference decisions.',
    callers: ['frontend: candidate-selector'],
    request_schema: 'PreferencesConfirmRequest',
    response_schema: 'PreferencesConfirmResponse',
    error_response_schema: ERR,
    constraints: {},
    query_params: {},
  },
  {
    type: 'rest',
    method: 'GET',
    path: '/api/projects/{id}/phases/{phase}/artifact',
    description: 'Fetch phase artifact payload (JSON or file URL).',
    callers: ['frontend: preview-component', 'render: theme-config'],
    request_schema: null,
    response_schema: 'ArtifactEnvelope',
    error_response_schema: null,
    constraints: {},
    query_params: {},
  },

  // --- Projects: events & costs ---
  {
    type: 'rest',
    method: 'GET',
    path: '/api/projects/{id}/events',
    description: 'Historical event list; paginated via limit + cursor.',
    callers: ['frontend: agent-activity-panel'],
    request_schema: null,
    response_schema: 'EventsResponse',
    error_response_schema: null,
    constraints: {},
    query_params: {
      limit: { type: 'integer', default: 50 },
      before: { type: 'cursor', default: null },
    },
  },
  {
    type: 'rest',
    method: 'GET',
    path: '/api/projects/{id}/costs',
    description: 'Project-level cost breakdown (total + by phase).',
    callers: ['frontend: cost-panel'],
    request_schema: null,
    response_schema: 'CostsResponse',
    error_response_schema: null,
    constraints: {},
    query_params: {},
  },

  // --- System ---
  {
    type: 'rest',
    method: 'GET',
    path: '/api/system/status',
    description: 'Pre-flight system status and degraded services list.',
    callers: ['frontend: system-banner'],
    request_schema: null,
    response_schema: 'SystemStatus',
    error_response_schema: null,
    constraints: {},
    query_params: {},
  },

  // --- Settings ---
  {
    type: 'rest',
    method: 'GET',
    path: '/api/settings',
    description: 'Fetch global settings (model_config + brand_kit).',
    callers: ['frontend: settings-page'],
    request_schema: null,
    response_schema: 'SettingsResponse',
    error_response_schema: null,
    constraints: {},
    query_params: {},
  },
  {
    type: 'rest',
    method: 'PUT',
    path: '/api/settings/model-config',
    description: 'Update global model configuration.',
    callers: ['frontend: settings-page'],
    request_schema: 'ModelConfig',
    response_schema: 'OkResponse',
    error_response_schema: ERR,
    constraints: {},
    query_params: {},
  },
  {
    type: 'rest',
    method: 'PUT',
    path: '/api/settings/brand-kit',
    description: 'Update brand kit (SQLite-only; no file writes).',
    callers: ['frontend: settings-page'],
    request_schema: 'BrandKit',
    response_schema: 'OkResponse',
    error_response_schema: ERR,
    constraints: { no_file_writes: true },
    query_params: {},
  },
  {
    type: 'rest',
    method: 'GET',
    path: '/api/settings/preferences',
    description: 'Fetch global user preferences markdown.',
    callers: ['frontend: settings-page'],
    request_schema: null,
    response_schema: 'PreferencesResponse',
    error_response_schema: null,
    constraints: {},
    query_params: {},
  },
  {
    type: 'rest',
    method: 'PUT',
    path: '/api/settings/preferences',
    description: 'Update global preferences; auto-creates snapshot.',
    callers: ['frontend: settings-page'],
    request_schema: 'PreferencesUpdateRequest',
    response_schema: 'PreferencesUpdateResponse',
    error_response_schema: ERR,
    constraints: { auto_snapshot: true },
    query_params: {},
  },
  {
    type: 'rest',
    method: 'GET',
    path: '/api/settings/preferences/snapshots',
    description: 'List preference snapshots (paginated via limit).',
    callers: ['frontend: settings-page'],
    request_schema: null,
    response_schema: 'SnapshotListResponse',
    error_response_schema: null,
    constraints: {},
    query_params: {
      limit: { type: 'integer', default: 20 },
    },
  },
  {
    type: 'rest',
    method: 'POST',
    path: '/api/settings/preferences/snapshots/{id}/rollback',
    description: 'Roll preferences back to a chosen snapshot.',
    callers: ['frontend: settings-page'],
    request_schema: null,
    response_schema: 'SnapshotRollbackResponse',
    error_response_schema: ERR,
    constraints: {},
    query_params: {},
  },

  // --- WebSocket ---
  {
    type: 'websocket',
    method: 'WS',
    path: '/ws/{project_id}',
    description: 'Real-time event stream per SPEC-11A envelope.',
    callers: ['frontend: workflow-page ws'],
    request_schema: null,
    response_schema: 'WsEventEnvelope',
    error_response_schema: null,
    constraints: {},
    query_params: {},
  },
] as const;
