# AUTOGENERATED from docs/BDD_ai_system_expected_behavior_v1.feature.md
# Do not edit by hand; amend the source .feature.md and re-run
# scripts/split_bdd_scenarios.py --apply

@decision @error-ux
Feature: 错误状态的 AI 决策与用户体验

  Scenario: 自动处理类错误不打断用户流程
    Given 系统错误码为 tts_api_timeout
    When 错误映射表转换为用户提示
    Then level 应为 auto_handling
    And 前端应展示 toast 而不是阻塞模态框
    And UI 中应显示预计自动恢复时间

  Scenario: 需要用户选择的错误必须阻塞并提供按钮
    Given 系统错误码为 financial_data_unavailable
    When 错误映射表转换为用户提示
    Then level 应为 user_choice
    And 前端应展示模态框
    And actions 应至少包含 manual_input 与 skip
    And 用户未选择前不应自动继续流程

  Scenario: 需要用户操作的错误必须红色强调
    Given 系统错误码为 worker_crash_max_retries
    When 错误映射表转换为用户提示
    Then level 应为 user_action
    And 前端应展示红色强调的模态框
    And actions 应至少包含 retry 或 go_back
