# AUTOGENERATED from docs/BDD_ai_system_expected_behavior_v1.feature.md
# Do not edit by hand; amend the source .feature.md and re-run
# scripts/split_bdd_scenarios.py --apply

@decision @gatekeeper
Feature: GateKeeper 阶段推进决策

  Scenario: 所有门禁满足时允许推进下一阶段
    Given 当前阶段主产物存在且非空
    And 当前阶段最新 review verdict 为 PASS
    And task_ledger 中不存在 pending、queued、running、timeout 状态任务
    And async_tasks 中不存在 running 状态任务
    And 当前阶段 preferences_confirmed_at 非空
    When 用户执行 confirm_next
    Then GateKeeper.check 应返回通过
    And FSM 应进入下一阶段
    And 新阶段 task_ledger 应被初始化

  Scenario: review 失败时阻塞推进
    Given 当前阶段最新 review verdict 为 FAIL
    When 用户执行 confirm_next
    Then GateKeeper.check 应返回失败
    And failure_reasons 中应包含审核未通过原因
    And 当前阶段不应推进

  Scenario: 主产物缺失时阻塞推进
    Given phases.current.artifact_ref 为空或指向文件不存在
    When 用户执行 confirm_next
    Then GateKeeper.check 应返回失败
    And failure_reasons 中应包含“主产物生成失败”或等价原因

  Scenario: 异步长任务仍在执行时阻塞推进
    Given 当前阶段存在 async_task.status=running
    When 用户执行 confirm_next
    Then GateKeeper.check 应返回失败
    And failure_reasons 中应包含“无进行中异步任务”未满足

  Scenario: skip_phase 仅走跳过分支门禁
    Given 当前阶段允许 skip_phase
    And phases.current.status 已标记为 skipped
    And 没有进行中任务
    And 当前阶段 preferences_confirmed_at 非空
    When 用户执行 confirm_next
    Then GateKeeper.check 应按跳过分支通过
    And 不要求当前阶段生成主产物或 review PASS
