# AUTOGENERATED from docs/BDD_ai_system_expected_behavior_v1.feature.md
# Do not edit by hand; amend the source .feature.md and re-run
# scripts/split_bdd_scenarios.py --apply

@navigation @ui
Feature: 项目列表与阶段回看

  Scenario: 用户进入首页后可以看到已生成的视频项目列表
    Given 系统中已存在多个视频项目
    When 用户打开首页 /
    Then 页面应展示项目列表
    And 每个项目至少显示标题、当前阶段、最近更新时间和项目状态
    And 用户应可以点击任一项目进入项目工作流页

  Scenario: 打开项目后自动展示最新阶段
    Given 某个项目当前 latest phase 为 Phase 7
    When 用户点击进入该项目
    Then 项目工作流页应默认高亮 Phase 7
    And 中间产物预览区应默认展示 Phase 7 的最新产物
    And 任务清单与对话区应默认切换到当前阶段上下文

  Scenario: 用户可以点击已完成阶段查看完整信息
    Given 某个项目已有多个 completed 阶段
    When 用户点击左侧任一已完成阶段
    Then 页面应展示该阶段的完整信息
    And 完整信息至少包含主产物、review 结果、关键事件、用户修改记录和偏好确认结果
    And 默认情况下该操作应为只读查看而不是立即回退重做
