# AUTOGENERATED from docs/BDD_ai_system_expected_behavior_v1.feature.md
# Do not edit by hand; amend the source .feature.md and re-run
# scripts/split_bdd_scenarios.py --apply

@observability @security
Feature: 可观测性、审计与脱敏

  Scenario: 每次 Agent 调用都必须留下四类证据
    Given 任意一次 Producer、Reviewer、Router 或 PreferenceExtractor 调用成功完成
    When 系统完成落库与落盘
    Then SQLite 中应存在对应 state 记录
    And events 表中应存在对应事件
    And agent_call_log 中应存在调用审计记录
    And 文件系统中应存在本次调用产出的主产物或更新后的产物文件

  Scenario: 敏感字段入库前必须脱敏
    Given 某次输入或输出文本中包含 API key、Bearer token、password 或 secret
    When 文本写入 agent_call_log.prompt、agent_call_log.response 或 events.payload
    Then 落库内容中的敏感片段应被替换为 [REDACTED]
    And scripts/leak_scan.py 抽样扫描的命中数应为 0

  Scenario: 成本记录失败只告警不阻塞门禁
    Given 当前阶段的 token 成本尚未成功写入 agent_call_log
    And 其他所有门禁条件都满足
    When 用户执行 confirm_next
    Then GateKeeper 不应仅因成本记录失败而阻塞推进
    And 系统应记录成本告警事件
