# AUTOGENERATED from docs/BDD_ai_system_expected_behavior_v1.feature.md
# Do not edit by hand; amend the source .feature.md and re-run
# scripts/split_bdd_scenarios.py --apply

@nonfunctional @performance
Feature: 性能与恢复性约束

  Scenario: Router 响应延迟必须满足交互要求
    Given 系统在正常运行且模型服务可用
    When 用户发送一条普通 revise 请求
    Then Router 调用 P95 应不超过 3 秒
    And Router 调用 P99 应不超过 5 秒

  Scenario: 用户关闭浏览器后长任务仍应恢复可见
    Given 某个 TTS 或渲染 async task 正在运行
    When 用户关闭浏览器并在稍后重新打开项目
    Then 系统应在 10 秒内恢复该项目的最新状态
    And 前端应可继续看到该长任务的进度、结果或失败信息
