# AUTOGENERATED from docs/BDD_ai_system_expected_behavior_v1.feature.md
# Do not edit by hand; amend the source .feature.md and re-run
# scripts/split_bdd_scenarios.py --apply

@generation @phase6 @sfx
Feature: Phase 6 音效设计

  Scenario: 音效设计前应先基于全文脚本给出全局关键词布局与理由
    Given Phase 5 已确认或跳过
    And 系统持有全文文本脚本与当前音频时间轴
    When SFXAgent 规划音效方案
    Then 应先识别哪些关键词、句子或叙事节点需要加音效
    And 每个音效提议都应说明加什么风格音效以及为什么加
    And 若某段不建议加音效 也应能解释不加的原因或遵循的稀疏原则

  Scenario: 前端应以全文标注形式展示全局音效布局
    Given SFXAgent 已生成初版全局音效规划
    When 前端展示 Phase 6 预览
    Then 用户应能在全文文本脚本上看到按词句或段落标注的音效布局
    And 每个标注至少展示音效类型、触发关键词、预计时间点和理由
    And 用户应能基于这些标注提出全局或局部改动建议

  Scenario: 用户确认布局后系统应按编号分段加工音频并支持逐段试听
    Given 用户已确认全局音效布局
    And Phase 5 已存在加工后的完整音频或明确跳过 BGM 的完整旁白音频
    When 系统开始执行音效叠加
    Then 应按时间轴把加工后的音频拆分为可定位的编号片段
    And 每个片段都应叠加对应的音效并生成可试听文件
    And 用户应可点击任意编号片段试听效果并提交修改建议
