# AUTOGENERATED from docs/BDD_ai_system_expected_behavior_v1.feature.md
# Do not edit by hand; amend the source .feature.md and re-run
# scripts/split_bdd_scenarios.py --apply

@audio @generation @phase4
Feature: Phase 4 TTS 决策与音频生成

  Scenario: TTS 应以异步长任务方式执行
    Given Gate 3 已通过
    When 用户启动旁白生成
    Then 系统应创建 generate_artifact 的 async task
    And async_tasks.status 应先为 pending 后变为 running
    And 关闭浏览器不应中断该任务
