# AUTOGENERATED from docs/BDD_ai_system_expected_behavior_v1.feature.md
# Do not edit by hand; amend the source .feature.md and re-run
# scripts/split_bdd_scenarios.py --apply

@generation @music @phase5
Feature: Phase 5 背景音乐生成与跳过决策

  Scenario: 用户选择跳过背景音乐
    Given 当前处于 Phase 5
    When 用户执行 skip_phase
    Then phases.phase_5.status 应为 skipped
    And 最终产物中应保留“BGM 已跳过”的状态信息
    And Gate 5 只检查无进行中任务和偏好确认完成

  Scenario: 用户试听时应听到混入 BGM 后的完整音频而不是单独 BGM
    Given Phase 4 已存在完整旁白音频
    And BGMAgent 已生成候选 BGM 与音量包络
    When 前端展示 Phase 5 预览内容
    Then 默认试听对象应为人声与 BGM 混合后的完整预览音频
    And 用户仍可查看或切换到单独 BGM 轨道作为辅助信息
    And 不应只提供脱离人声语境的 BGM 单独试听作为主决策依据
