# AUTOGENERATED from docs/BDD_ai_system_expected_behavior_v1.feature.md
# Do not edit by hand; amend the source .feature.md and re-run
# scripts/split_bdd_scenarios.py --apply

@delivery @generation @phase11
Feature: Phase 11 精剪交付与多平台适配

  Scenario: 最终交付必须覆盖所有目标平台
    Given Phase 0 指定 primary=bilibili 且 secondary 包含 douyin
    When FinalCutAgent 完成导出
    Then phase_11 目录下至少应存在 bilibili 与 douyin 两个平台版本 mp4
    And 各文件分辨率与码率应符合对应平台规格

  Scenario: 封面必须至少提供 3 个可选方案
    Given 进入 Phase 11 封面生成子任务
    When FinalCutAgent 输出封面
    Then 应至少生成 3 个封面方案
    And 每个封面应包含主题文字、品牌元素与关键数据
    And 封面尺寸应符合平台规格

  Scenario: 最终门禁通过后项目进入只读完成态
    Given FinalReviewer verdict 为 PASS
    And 所有平台文件、封面文件和字幕文件都存在
    And 导出 async_task.status 为 done
    And preferences_confirmed_at 非空
    When Gate 11 通过
    Then project.status 应变为 completed
    And project.completed_at 应被写入
    And 前端应切换为只读模式
    And 用户仍可下载产物但不可继续修改当前完成版
