# AUTOGENERATED from docs/BDD_ai_system_expected_behavior_v1.feature.md
# Do not edit by hand; amend the source .feature.md and re-run
# scripts/split_bdd_scenarios.py --apply

@generation @phase8 @render
Feature: Phase 8 关键画面渲染与降级

  Scenario: 单个 shot 渲染失败时应局部降级而非整体失败
    Given 某个 template shot 渲染异常
    When KeyframeRenderAgent 处理该 shot
    Then 该 shot 应降级为默认文字卡
    And 其他 shot 继续正常渲染
    And render_results.json 中应记录该 shot 的 degraded 状态与原因

  Scenario: Gate 8 允许少量降级但要求总体成功率达标
    Given 本批次 template shot 总数为 20 个
    And 其中 2 个 shot 被降级
    When VisualReviewer 完成审核
    Then 渲染成功率应为 90% 或以上
    And Gate 8 可通过
