# AUTOGENERATED from docs/BDD_ai_system_expected_behavior_v1.feature.md
# Do not edit by hand; amend the source .feature.md and re-run
# scripts/split_bdd_scenarios.py --apply

@editing @generation @phase10
Feature: Phase 10 粗剪合成

  Scenario: 粗剪必须按时间轴拼接全部画面与音轨
    Given Phase 4、5、6、8、9 的输入产物都已准备完成或被合法跳过
    When RoughCutAgent 执行合成
    Then 输出应包含视觉轨、音频轨与字幕轨
    And 所有分镜 shot 应按顺序出现
    And 输出文件 rough_cut_v1.mp4 应存在且可播放
