# AUTOGENERATED from docs/BDD_ai_system_expected_behavior_v1.feature.md
# Do not edit by hand; amend the source .feature.md and re-run
# scripts/split_bdd_scenarios.py --apply

@decision @preferences
Feature: PreferenceExtractor 偏好提取与确认

  Scenario: nothing_found 仍需用户显式完成门禁动作
    Given 本阶段没有任何可复用偏好
    When 用户点击 confirm_next
    Then PreferenceExtractor 应输出 nothing_found=true
    And candidates 应为空数组
    And 前端仍需要求用户点击一次“跳过”或等价确认按钮
    And phases.current.preferences_confirmed_at 在用户点击前必须为空
