# AUTOGENERATED from docs/BDD_ai_system_expected_behavior_v1.feature.md
# Do not edit by hand; amend the source .feature.md and re-run
# scripts/split_bdd_scenarios.py --apply

@audio @preferences
Feature: 音频参数的全局调整、局部微调与偏好回写

  Scenario: 音频完成后系统应比较实际设置与偏好差异并建议是否回写
    Given 当前阶段已成功生成一版用户认可的音频
    And 本次实际音频设置与现有偏好存在差异
    When 用户准备 confirm_next
    Then PreferenceExtractor 或音频偏好比较器应识别这些差异
    And 应向用户建议哪些适合更新为全局偏好、项目偏好或阶段偏好
    And 未经用户确认 不应自动覆盖既有偏好
