# AUTOGENERATED from docs/BDD_ai_system_expected_behavior_v1.feature.md
# Do not edit by hand; amend the source .feature.md and re-run
# scripts/split_bdd_scenarios.py --apply

@classification @router
Feature: IntentRouter 动作分类

  Scenario: Router 超时或 JSON 解析失败时回退 clarify
    Given Router 模型调用超时或返回非 JSON 文本
    When API 层尝试解析 Router 输出
    Then 系统应回退为 clarify
    And 不应猜测用户意图
    And events 中应记录 router.intent_fallback 或等价事件
