#!/usr/bin/env python3
"""[GAPFIX-029] Generate typed routes SDK from API_ROUTES contract.

Generates two files from ``src/shared/contracts/api_routes.py``:
  - src/shared/generated/routes_sdk.py   (typed Python stubs)
  - src/shared/generated/routes_sdk.ts   (typed TypeScript fetch functions)

Usage:
  python3 scripts/generate_routes_sdk.py             # generate both files
  python3 scripts/generate_routes_sdk.py --check     # verify existing files match
  python3 scripts/generate_routes_sdk.py --help
"""
from __future__ import annotations

import argparse
import os
import re
import sys
from typing import Any, Dict, List, Optional, Tuple

PROJECT_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, PROJECT_ROOT)

from src.shared.contracts.api_routes import API_ROUTES  # noqa: E402

PY_SDK_PATH = os.path.join(PROJECT_ROOT, "src", "shared", "generated", "routes_sdk.py")
TS_SDK_PATH = os.path.join(PROJECT_ROOT, "src", "shared", "generated", "routes_sdk.ts")


# ---------------------------------------------------------------------------
# helpers
# ---------------------------------------------------------------------------

def _strip_api_prefix(path: str) -> str:
    for prefix in ("/api/", "/ws/"):
        if path.startswith(prefix):
            return path[len(prefix):]
    return path.lstrip("/")


def _is_path_param(seg: str) -> bool:
    return seg.startswith("{") and seg.endswith("}")


def _simple_singularize(word: str) -> str:
    """Heuristic singular: strip trailing 's' for simple plurals."""
    if word.endswith("ies"):
        return word[:-3] + "y"
    if word.endswith("sses"):
        return word[:-2]
    if word.endswith("s") and not word.endswith("ss") and not word.endswith("us"):
        return word[:-1]
    return word


def _to_pascal(segments: List[str]) -> str:
    """Build PascalCase from segments, handling hyphens."""
    result = ""
    for seg in segments:
        if not seg:
            continue
        for sub in seg.split("-"):
            if sub:
                result += sub[0].upper() + sub[1:]
    return result


def _extract_path_params(path: str) -> List[str]:
    """Extract path parameter names (without braces)."""
    return [s.strip("{}") for s in path.split("/") if _is_path_param(s)]


def _derive_fn_name(route: Dict[str, Any]) -> str:
    method = route["method"]
    path = route["path"]
    clean = _strip_api_prefix(path)
    raw = clean.strip("/").split("/")

    literals: List[str] = []
    for i, seg in enumerate(raw):
        if _is_path_param(seg):
            continue
        followed_by_param = (i + 1 < len(raw) and _is_path_param(raw[i + 1]))
        if followed_by_param:
            literals.append(_simple_singularize(seg))
        else:
            literals.append(seg)

    if method == "GET":
        return "get" + _to_pascal(literals)
    if method == "DELETE":
        return "delete" + _to_pascal(literals)
    if method == "PUT":
        return "update" + _to_pascal(literals)
    if method == "POST":
        if len(literals) > 1:
            verb = literals[-1]
            nouns = literals[:-1]
            return verb + _to_pascal(nouns)
        return "create" + _to_pascal([_simple_singularize(l) for l in literals])
    if method == "WS":
        ws_parts = [s.strip("{}") for s in raw]
        return "connect" + _to_pascal(ws_parts) + "Ws"
    return "unknown"


# ---------------------------------------------------------------------------
# generators
# ---------------------------------------------------------------------------

def _generate_python_sdk() -> str:
    lines: List[str] = []
    lines.append('"""Auto-generated typed routes SDK for Python clients.')
    lines.append("")
    lines.append('Generated by: scripts/generate_routes_sdk.py')
    lines.append('Source:      src/shared/contracts/api_routes.py')
    lines.append('"""')
    lines.append("from __future__ import annotations")
    lines.append("")
    lines.append("from typing import Any, Dict, Optional, List, Tuple")
    lines.append("")

    # Collect all type references for imports
    type_refs: set[str] = set()
    for route in API_ROUTES:
        for k in ("request_schema", "response_schema", "error_response_schema"):
            v = route.get(k)
            if v:
                type_refs.add(v)

    req_types = sorted([t for t in type_refs if t.endswith("Request") and t != "ErrorResponse"])
    resp_types = sorted([
        t for t in type_refs
        if (t.endswith("Response") or t == "ErrorResponse" or t == "OkResponse"
            or t == "ProjectInfo" or t == "ProjectState" or t == "ArtifactEnvelope"
            or t == "Preferences" or t == "ModelConfig" or t == "BrandKit"
            or t == "SystemStatus" or t == "WsEventEnvelope")
    ])

    if req_types:
        lines.append("# Import schema types from the shared contracts layer.")
        lines.append("from src.shared.contracts.api_requests import (")
        for t in req_types:
            lines.append(f"    {t},")
        lines.append(")")
        lines.append("")

    if resp_types:
        lines.append("from src.shared.contracts.api_responses import (")
        for t in resp_types:
            lines.append(f"    {t},")
        lines.append(")")
        lines.append("")

    lines.append("")
    lines.append("class RoutesSdk:")
    lines.append('    """Typed method stubs for all API routes listed in API_ROUTES."""')
    lines.append("")

    for route in API_ROUTES:
        fn_name = _derive_fn_name(route)
        method = route["method"]
        path = route["path"]
        params = _extract_path_params(path)
        query = route.get("query_params", {})
        req_schema = route.get("request_schema")
        resp_schema = route.get("response_schema", "None")
        desc = route.get("description", "")

        fn_params: List[str] = ["self"]
        for p in params:
            fn_params.append(f"{p}: str")
        if req_schema:
            fn_params.append(f"body: {req_schema}")
        if query:
            fn_params.append("params: Optional[Dict[str, Any]] = None")

        lines.append(f"    def {fn_name}({', '.join(fn_params)}) -> {resp_schema}:")
        lines.append(f'        """{desc}')
        lines.append(f"")
        lines.append(f"        {method} {path}")
        lines.append(f'        """')
        lines.append(f"        ...  # auto-generated stub")
        lines.append("")

    lines.append("")
    lines.append('__all__ = ["RoutesSdk"]')
    return "\n".join(lines) + "\n"


def _generate_typescript_sdk() -> str:
    lines: List[str] = []
    lines.append("// Auto-generated typed routes SDK for TypeScript clients.")
    lines.append("// Generated by: scripts/generate_routes_sdk.py")
    lines.append("// Source:      src/shared/contracts/api_routes.py")
    lines.append("")

    ts_types: set[str] = set()
    for route in API_ROUTES:
        for k in ("request_schema", "response_schema"):
            v = route.get(k)
            if v:
                ts_types.add(v)

    lines.append("import type {")
    for t in sorted(ts_types):
        lines.append(f"  {t},")
    lines.append("} from '../contracts/api_types';")
    lines.append("")

    lines.append("// eslint-disable-next-line @typescript-eslint/no-explicit-any")
    lines.append("type ApiClient = {")
    lines.append("  get: <T>(url: string, params?: Record<string, unknown>) => Promise<T>;")
    lines.append("  post: <T>(url: string, body?: unknown) => Promise<T>;")
    lines.append("  put: <T>(url: string, body?: unknown) => Promise<T>;")
    lines.append("  del: <T>(url: string) => Promise<T>;")
    lines.append("};")
    lines.append("")
    lines.append("export function createRoutesSdk(client: ApiClient) {")
    lines.append("  return {")

    rest_routes = [r for r in API_ROUTES if r["method"] != "WS"]

    for i, route in enumerate(rest_routes):
        fn_name = _derive_fn_name(route)
        method = route["method"]
        path = route["path"]
        params = _extract_path_params(path)
        query = route.get("query_params", {})
        req_schema = route.get("request_schema")
        resp_schema = route.get("response_schema", "void")
        desc = route.get("description", "")

        url_expr = "`" + re.sub(r"\{(\w+)\}", r"${\1}", path) + "`"

        fn_params: List[str] = []
        for p in params:
            fn_params.append(f"{p}: string")
        if req_schema:
            fn_params.append(f"body: {req_schema}")
        if query:
            fn_params.append("params?: Record<string, unknown>")

        if method == "GET":
            args = "params" if query else ""
            http_call = f"client.get<{resp_schema}>({url_expr}{', ' + args if args else ''})"
        elif method == "POST":
            args = "body" if req_schema else "undefined"
            http_call = f"client.post<{resp_schema}>({url_expr}, {args})"
        elif method == "PUT":
            args = "body" if req_schema else "undefined"
            http_call = f"client.put<{resp_schema}>({url_expr}, {args})"
        elif method == "DELETE":
            http_call = f"client.del<{resp_schema}>({url_expr})"
        else:
            continue

        comma = "," if i < len(rest_routes) - 1 else ""
        lines.append(f"    // {method} {path}")
        lines.append(f"    // {desc[:80]}")
        lines.append(f"    {fn_name}({', '.join(fn_params)}): Promise<{resp_schema}> {{")
        lines.append(f"      return {http_call};")
        lines.append(f"    }}{comma}")
        lines.append("")

    lines.append("  };")
    lines.append("}")
    return "\n".join(lines) + "\n"


# ---------------------------------------------------------------------------
# check mode
# ---------------------------------------------------------------------------

def _read_if_exists(path: str) -> Optional[str]:
    try:
        with open(path, "r", encoding="utf-8") as f:
            return f.read()
    except FileNotFoundError:
        return None


def _check_mode() -> int:
    exit_code = 0
    expected_py = _generate_python_sdk()
    current_py = _read_if_exists(PY_SDK_PATH)
    if current_py is None:
        print(f"MISSING: {PY_SDK_PATH} does not exist")
        exit_code = 1
    elif current_py != expected_py:
        print(f"STALE: {PY_SDK_PATH} differs from generated output")
        exit_code = 1
    else:
        print(f"OK: {PY_SDK_PATH} matches current API_ROUTES")

    expected_ts = _generate_typescript_sdk()
    current_ts = _read_if_exists(TS_SDK_PATH)
    if current_ts is None:
        print(f"MISSING: {TS_SDK_PATH} does not exist")
        exit_code = 1
    elif current_ts != expected_ts:
        print(f"STALE: {TS_SDK_PATH} differs from generated output")
        exit_code = 1
    else:
        print(f"OK: {TS_SDK_PATH} matches current API_ROUTES")

    return exit_code


# ---------------------------------------------------------------------------
# main
# ---------------------------------------------------------------------------

def main() -> int:
    parser = argparse.ArgumentParser(
        description="Generate typed routes SDK from API_ROUTES contract."
    )
    parser.add_argument(
        "--check", action="store_true",
        help="Verify generated files match current API_ROUTES"
    )
    args = parser.parse_args()

    if args.check:
        return _check_mode()

    os.makedirs(os.path.dirname(PY_SDK_PATH), exist_ok=True)

    py_content = _generate_python_sdk()
    with open(PY_SDK_PATH, "w", encoding="utf-8") as f:
        f.write(py_content)
    print(f"Generated: {PY_SDK_PATH} ({len(py_content.splitlines())} lines)")

    ts_content = _generate_typescript_sdk()
    with open(TS_SDK_PATH, "w", encoding="utf-8") as f:
        f.write(ts_content)
    print(f"Generated: {TS_SDK_PATH} ({len(ts_content.splitlines())} lines)")

    return 0


if __name__ == "__main__":
    sys.exit(main())
